Repository WellyKorgis/project-blind-api, pull requests merged in 2022-04, with the labels that each got.

#7 Issue #5: Create PR template
  .github/pull_request_template.md
Labels: documentation, dev practices, D+3

#6 Doc: Update README.md to provide dev guideline
  README.md
Labels: documentation, dev practices, D+3

#8 Create docker-compose.yml
  docker-compose.yml
Labels: D+3

#9 Github Action: Remove workflow from master
  .github/workflows/discord-message-trigger.yml
Labels: bug

#18 Issue#11: Add ORM (JPA) to create a db in postgreSQL
  .gitignore
  Dockerfile
  build.gradle
  docker-compose.yml
  settings.gradle
  src/main/java/com/blind/api/ApiApplication.java
  src/main/java/com/blind/api/user/domain/User.java
  src/main/java/com/blind/api/user/repository/UserRepository.java
  src/main/java/com/blind/common/domain/BaseEntity.java
  src/main/resources/application.properties
  src/test/java/com/blind/api/ApiApplicationTests.java
Labels: db, D+2

#20 Issue #12, #14: Add Company and CompanyCategory entities
  src/main/java/com/blind/api/company/domain/Company.java
  src/main/java/com/blind/api/company/domain/CompanyCategory.java
  src/main/java/com/blind/api/company/repository/CompanyCategoryRepository.java
  src/main/java/com/blind/api/company/repository/CompanyRepository.java
  src/main/java/com/blind/api/user/domain/User.java
  src/main/resources/application.properties
Labels: D+3, db

#30 Merge Main into Develop
  .github/pull_request_template.md
  .gitignore
  Dockerfile
  README.md
  build.gradle
  docker-compose.yml
  settings.gradle
  src/main/java/com/blind/api/ApiApplication.java
  src/main/java/com/blind/api/user/domain/User.java
  src/main/java/com/blind/api/user/repository/UserRepository.java
  src/main/java/com/blind/common/domain/BaseEntity.java
  src/main/resources/application.properties
  src/test/java/com/blind/api/ApiApplicationTests.java
Labels: dev practices

#22 Issue #15, #16: Add Job Position and Job Category entities
  src/main/java/com/blind/api/job/domain/JobCategory.java
  src/main/java/com/blind/api/job/domain/JobPosition.java
  src/main/java/com/blind/api/job/repository/JobCategoryRepository.java
  src/main/java/com/blind/api/job/repository/JobPositionRepository.java
  src/main/java/com/blind/api/user/domain/User.java
  src/main/resources/application.properties
Labels: db, D+2
