Repository WellyKorgis/project-blind-api, pull requests merged in 2022-05, with the labels that each got.

#40 Add book mark
  src/main/java/com/blind/api/bookmark/domain/Bookmark.java
  src/main/java/com/blind/api/bookmark/repository/BookmarkRepository.java
  src/main/java/com/blind/api/job/domain/JobCategory.java
  src/main/java/com/blind/api/job/domain/JobPosition.java
  src/main/java/com/blind/api/job/repository/JobCategoryRepository.java
  src/main/java/com/blind/api/job/repository/JobPositionRepository.java
  src/main/java/com/blind/api/post/domain/Post.java
  src/main/java/com/blind/api/post/repository/PostRepository.java
  src/main/java/com/blind/api/user/domain/User.java
Labels: D+3

#43 Add comment domain and its repository
  src/main/java/com/blind/api/comment/domain/Comment.java
  src/main/java/com/blind/api/comment/repository/CommentRepository.java
Labels: D+2

#46 Add tag
  src/main/java/com/blind/api/tag/domain/Tag.java
  src/main/java/com/blind/api/tag/persistence/TagRepository.java
Labels: D+2

#51 Update gitignore and move files into project-blind folder
  .github/danger.yml
  .gitignore
  dangerfile.ts
  package.json
  project-blind/Dockerfile
  project-blind/build.gradle
  project-blind/docker-compose.yml
  project-blind/settings.gradle
  project-blind/src/main/java/com/blind/BlindApplication.java
  project-blind/src/main/java/com/blind/account/api/AccountController.java
  project-blind/src/main/java/com/blind/account/domain/Account.java
  project-blind/src/main/java/com/blind/account/persistence/repository/AccountRepository.java
  project-blind/src/main/java/com/blind/company/api/CompanyController.java
  project-blind/src/main/java/com/blind/company/api/JobController.java
  project-blind/src/main/java/com/blind/company/domain/Company.java
  project-blind/src/main/java/com/blind/company/domain/CompanyCategory.java
  project-blind/src/main/java/com/blind/company/domain/JobCategory.java
  project-blind/src/main/java/com/blind/company/domain/JobPosition.java
  project-blind/src/main/java/com/blind/company/persistence/respository/CompanyCategoryRepository.java
  project-blind/src/main/java/com/blind/company/persistence/respository/CompanyRepository.java
  project-blind/src/main/java/com/blind/company/persistence/respository/JobCategoryRepository.java
  project-blind/src/main/java/com/blind/company/persistence/respository/JobPositionRepository.java
  project-blind/src/main/java/com/blind/post/api/CommentController.java
  project-blind/src/main/java/com/blind/post/api/PostController.java
  project-blind/src/main/java/com/blind/post/domain/Bookmark.java
  project-blind/src/main/java/com/blind/post/domain/Comment.java
  project-blind/src/main/java/com/blind/post/domain/Post.java
  project-blind/src/main/java/com/blind/post/domain/Tag.java
  project-blind/src/main/java/com/blind/post/persistence/repository/BookmarkRepository.java
  project-blind/src/main/java/com/blind/post/persistence/repository/CommentRepository.java
  project-blind/src/main/java/com/blind/post/persistence/repository/PostRepository.java
  project-blind/src/main/java/com/blind/post/persistence/repository/TagRepository.java
  project-blind/src/main/java/com/blind/shared/domain/BaseEntity.java
  project-blind/src/main/resources/application.properties
  project-blind/src/test/java/com/blind/api/ApiApplicationTests.java
  tsconfig.json
Labels: devops, dev practices, D+3

#49 Add post category
  src/main/java/com/blind/post/domain/PostCategory.java
  src/main/java/com/blind/post/persistence/repository/PostCategoryRepository.java
Labels: feature, D+2

#53 Feature/post controller
  src/main/java/com/blind/account/domain/Account.java
  src/main/java/com/blind/company/domain/Company.java
  src/main/java/com/blind/post/api/PostController.java
  src/main/java/com/blind/post/domain/Post.java
Labels: feature
