Repository WellyKorgis/project-blind-api, pull requests merged in 2022-06, with the labels that each got.

#60 Get a company by id
  build.gradle
  docker-compose.yml
  src/main/java/com/blind/account/domain/Account.java
  src/main/java/com/blind/company/api/CompanyController.java
  src/main/java/com/blind/company/api/controller/CompanyController.java
  src/main/java/com/blind/company/api/controller/JobController.java
  src/main/java/com/blind/company/api/dto/response/CompanyCategoryResponse.java
  src/main/java/com/blind/company/api/dto/response/CompanyResponse.java
  src/main/java/com/blind/company/api/mapper/CompanyMapper.java
  src/main/java/com/blind/company/api/service/CompanyService.java
  src/main/java/com/blind/company/api/service/CompanyServiceImpl.java
  src/main/java/com/blind/company/domain/Company.java
  src/main/java/com/blind/company/domain/CompanyCategory.java
  src/main/java/com/blind/company/domain/JobPosition.java
  src/main/java/com/blind/company/persistence/respository/CompanyCategoryRepository.java
  src/main/java/com/blind/company/persistence/respository/CompanyRepository.java
  src/main/java/com/blind/company/persistence/respository/JobCategoryRepository.java
  src/main/java/com/blind/company/persistence/respository/JobPositionRepository.java
  src/main/java/com/blind/post/api/PostController.java
  src/main/java/com/blind/shared/api/BaseDtoResponse.java
  src/main/java/com/blind/shared/domain/BaseEntity.java
  src/test/java/com/blind/api/ApiApplicationTests.java
  src/test/java/com/blind/api/controller/CompanyControllerTests.java
  src/test/java/com/blind/api/mapping/MappingTests.java
Labels: D+3, feature

#64 Seegya/feature/swagger
  build.gradle
  src/main/java/com/blind/post/api/PostController.java
  src/main/java/com/blind/shared/config/SwaggerConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: D+3, feature

#75 Add a new GET method to find a post by its id
  src/main/java/com/blind/post/api/PostController.java
Labels: D+3

#69 Auto populdate dummy data for company
  Dockerfile
  build.gradle
  src/main/java/com/blind/company/domain/Company.java
  src/main/java/com/blind/company/domain/CompanyCategory.java
  src/main/java/com/blind/shared/persistence/CompanyData.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/company-data.json
Labels: enhancement, D+3

#76 Controller/add post
  build.gradle
  src/main/java/com/blind/post/api/PostController.java
  src/main/java/com/blind/post/domain/Post.java
Labels: D+3

#77 Add deletePost method
  src/main/java/com/blind/post/api/PostController.java
Labels: D+3
